name: Update readme with blog posts
on: 
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://quyln.com/rss.xml
          readme-section: feed
          template: "#### [{{ title }}]({{ link }}) \n"
